<?php

namespace Intranet\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSubmissionRepository extends EntityRepository
{
}
