<?php

namespace Intranet\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupRepository extends EntityRepository
{
    public function findProjectGroup($project_id, $user_id)
    {        
        $queryBuilder = $this->createQueryBuilder('pg');

        $queryBuilder = $this->_em->createQueryBuilder()
                                  ->select('pg')
                                  ->from($this->_entityName, 'pg')
                                  ->leftJoin('pg.users', 'u')
                                  ->leftJoin('pg.project', 'p')
                                  ->where('p.id = :project_id')
                                  ->setParameter('project_id', $project_id);
                                  //->setParameter('user_id', $user_id);

        $query = $queryBuilder->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
