<?php

namespace Intranet\WikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function searchWikiContent($search)
    {
        $result = $this->_em->createQueryBuilder()
                    ->select('m')
                    ->from('IntranetWikiBundle:Modif', 'm')
                    ->join('m.article', 'a')
                    ->where('m.content LIKE :search')
                    ->orWhere('a.name LIKE :search')
                    ->setParameter('search', '%' . $search . '%')
                    ->getQuery()
                    ->getResult();
        
        return $result;
    }
}
