<?php

namespace Intranet\WikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModifRepository extends EntityRepository
{
}
