jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Intranet\UserBundle\Entity\User: sha512


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_TEACHER, ROLE_STUDENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # On crée un pare-feu uniquement pour le formulaire
        main_login:
          pattern:   ^/login$
          anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%

    access_control:
        - { path: ^/img/*, roles: IS_FULLY_AUTHENTICATED }
