news:
    providers:
        - sonata.media.provider.dailymotion
        - sonata.media.provider.youtube
        - sonata.media.provider.image

    formats:
        small: { width: 150 , quality: 95}
        big:   { width: 500 , quality: 90}