<?php

namespace Intranet\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function postNotification($title, $content)
    {
        $em = $this->_em;
        
         $article = new Article();
         $article->setTitle($title);
         $article->setContent($content);
         $article->setDate(new \DateTime());
         
         $em->persist($article);
         $em->flush();
    }
}
