<?php

namespace Intranet\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictoNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictoNewsRepository extends EntityRepository
{
}
