<?php

namespace Intranet\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMemberRepository extends EntityRepository
{
}
