<?php

namespace Intranet\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicViewRepository extends EntityRepository
{
    public function hasReadTopic($user, $topic)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
                ->select('tv')
                ->from($this->_entityName, 'tv')
                ->where('tv.user = :user')
                ->andWhere('tv.topic = :topic')
                ->setParameter('user', $user)
                ->setParameter('topic', $topic);

        $query = $queryBuilder->getQuery();

        $result = $query->getOneOrNullResult();

        return $result !== null;
    }
    
    public function getLastPost($topic)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
                ->select('p')
                ->from('IntranetForumBundle:Post', 'p')
                ->where('p.topic = :topic')
                ->orderBy('p.createdAt', 'ASC')
                ->setParameter('topic', $topic);

        $query = $queryBuilder->getQuery();

        $result = $query->getResult();

        if (count($result) > 0)
            return $result[0];
        else
            return null;
    }
}
