<?php

namespace Intranet\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseTypeRepository extends EntityRepository
{
}
