<?php

namespace Intranet\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseTypeRepository extends EntityRepository
{
    public function makeAllGhost()
    {
        $qb = $this->_em->createQueryBuilder()
            ->update($this->_entityName, 's')
            ->set('s.number', 0);
        $q = $qb->getQuery();
        $p = $q->execute();
        
    }
}
