<?php

namespace Intranet\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAssignmentRepository extends EntityRepository
{
}
