<?php

namespace Intranet\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAssignmentRepository extends EntityRepository
{
    public function makeTicketUnread($id)
    {
        $qb = $this->_em->createQueryBuilder()
            ->update($this->_entityName, 's')
            ->where('s.ticket >= :id')
            ->set('s.isRead', 0)
            ->setParameter('id', $id, \Doctrine\DBAL\Types\Type::INTEGER);
        $q = $qb->getQuery();
        $p = $q->execute();
        
    }
}
